import { chromium } from 'playwright';
import assert from 'node:assert/strict';
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH});
try {
const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error'&&!m.text().includes('status of 404')&&!m.text().includes('status of 500'))errors.push(m.text())});
await page.goto(`${process.env.LCR_WEB_URL ?? 'http://127.0.0.1:4173'}/#/fit`);
await page.locator('input[type=file]').setInputFiles({name:'r.csv',mimeType:'text/csv',buffer:Buffer.from('f,re,im\n10,1000,0\n100,1000,0\n1000,1000,0\n10000,1000,0\n')});
await page.getByPlaceholder('不填 = 自由搜索').fill('1');
await page.getByRole('button',{name:'运行 Try 1',exact:true}).click();
await page.locator('.cand-table').waitFor({timeout:120000});console.log('Try1 PASS');
await page.getByText('Try 3 · 已知拓扑',{exact:true}).click();
await page.locator('textarea').fill('0 2 R\n2 1 R\n0 3 C');
await page.getByRole('button',{name:'运行 Try 3',exact:true}).click();
await page.getByText('Try 3 拟合诊断',{exact:true}).waitFor();
assert.match(await page.locator('body').innerText(),/ser/);console.log('Try3 merged PASS');
await page.locator('textarea').fill('0 2 R');
await page.getByRole('button',{name:'运行 Try 3',exact:true}).click();
await page.getByText('端口开路：拓扑在 0–1 端口间不导通',{exact:false}).waitFor();console.log('port open PASS');
await page.getByText('Try 2 · 已知元件',{exact:true}).click();
await page.getByRole('button',{name:'删除',exact:true}).last().click();await page.getByRole('button',{name:'删除',exact:true}).last().click();
await page.getByRole('button',{name:'运行 Try 2',exact:true}).click();
await page.locator('.cand-table').waitFor();assert.match(await page.locator('body').innerText(),/有限候选空间最优已验证/);console.log('Try2 pure R PASS');
await page.getByText('Try 1 · 未知辨识',{exact:true}).click();
await page.getByPlaceholder('不填 = 自由搜索').fill('6');
await page.getByRole('button',{name:'运行 Try 1',exact:true}).click();
await page.getByRole('button',{name:'取消',exact:true}).click();
await page.getByText('已取消',{exact:true}).waitFor();console.log('cancel PASS');
await page.getByPlaceholder('不填 = 自由搜索').fill('1');
await page.getByRole('button',{name:'运行 Try 1',exact:true}).click();await page.locator('.cand-table').waitFor();console.log('restart PASS');
await page.getByText('Try 3 · 已知拓扑',{exact:true}).click();
await page.locator('textarea').fill('0 1 L\n0 1 L\n0 1 L');
await page.getByRole('button',{name:'运行 Try 3',exact:true}).click();
await page.getByText('Try 3 拟合诊断',{exact:true}).waitFor();
assert.match(await page.locator('.cand-table').innerText(),/—/);console.log('null AICc PASS');
await page.getByText('Try 1 · 未知辨识',{exact:true}).click();
await page.getByLabel('时间预算 / 秒（0 不限）').fill('0.000000001');
await page.getByPlaceholder('不填 = 自由搜索').fill('6');
await page.getByRole('button',{name:'运行 Try 1',exact:true}).click();
await page.getByText('没有数值可靠的候选；可增加预算或检查输入。',{exact:true}).waitFor();
assert.match(await page.locator('body').innerText(),/部分搜索结果/);console.log('empty partial result PASS');
console.log('errors',errors);assert.equal(errors.length,0);
if(process.env.LCR_SCREENSHOT)await page.screenshot({path:process.env.LCR_SCREENSHOT,fullPage:true});
} finally { await browser.close(); }
